# Generated by Django 2.1.7 on 2019-03-12 20:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='user_subscribers', to=settings.AUTH_USER_MODEL, verbose_name="Blog's subscribers"),
        ),
        migrations.AlterField(
            model_name='post',
            name='blog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='blogs.Blog'),
        ),
    ]
